version: "3"
services:
  app:
    image: "baturayucer-image-service"
    build: ./
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
    volumes:
      - ~/.aws/:/root/.aws:ro